<a href="https://colab.research.google.com/github/RadimKozl/PyTorch_Samples/blob/main/pyTorch_sample1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
from torchvision import transforms
from PIL import Image

**Float Tensor sample**

In [2]:
float_tensor = torch.FloatTensor([3,3])
print(type(float_tensor), float_tensor)

<class 'torch.Tensor'> tensor([3., 3.])


**Long Tensor sample**

In [3]:
long_tensor = torch.LongTensor([3,3])
print(type(long_tensor), long_tensor)

<class 'torch.Tensor'> tensor([3, 3])


**Bool Tensor sample**

In [4]:
bool_tensor = torch.BoolTensor([True, False])
bool_tensor

tensor([ True, False])

**No_grad Context Manager**

In [5]:
x = torch.tensor([1.], requires_grad=True)

with torch.no_grad():
  y = x * 2
  print(y)

tensor([2.])


**torchvision: Compose Object**

In [6]:
from google.colab import files

uploaded = files.upload()

for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.
        format(name=fn, length=len(uploaded[fn])))

Saving SVmetalLogo.png to SVmetalLogo.png
User uploaded file "SVmetalLogo.png" with length 5077 bytes


In [7]:
x = Image.open('SVmetalLogo.png')
transform = transforms.Compose([
    transforms.PILToTensor(),
    transforms.ConvertImageDtype(torch.float)
])

tensor_x = transform(x)
tensor_x

tensor([[[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]]])